version: 2
updates:
- package-ecosystem: npm
  directory: "/javascript"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/ruby"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
